# Generated by Django 5.1.5 on 2025-01-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task_Management_System", "0003_remove_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
